### ISSUE TITLE
Allow `![]const u8` to also be used as a reference

### ISSUE THREAD

**Issue by stephenafamo** [jetzig-framework/zmpl#34]

**Comment by bobf** [comment]
@stephenafamo Can you give an example use case for this ? One I can think of is e.g.:
```
{{foo(bar)}}
```
but then couldn't you use `try` ?
```
{{try foo(bar)}}
```

**Comment by bobf** [comment]
If you think the above PR solves your issue then I'm happy to merge. Seems like it could be convenient for other things too.

**Comment by bobf** [comment]
@stephenafamo `zmpl.write` now resolves optionals and error unions - I agree this is cleaner, thanks for the suggestion.
