### ISSUE TITLE
Multiline tailwind code not supported

### ISSUE THREAD

**Issue by dhrubrawat66** [jetzig-framework/zmpl#8]
1. icreate the simple project with jetzig
2.  run by using the zig build run, and it compiled as below
![yes](https://github.com/jetzig-framework/zmpl/assets/85351405/7e1bb11e-5c02-4b9a-b716-b4740df3eee3)
4.  but when break the code in to multiple line it throw error as below
![no](https://github.com/jetzig-framework/zmpl/assets/85351405/105e09da-f5a5-45eb-ac69-fd0f9f7b5f50)

-- i'm using the windwo os 11.

**Comment by bobf** [comment]
Thanks a lot for raising this, @dhrubrawat66 - I'll update the Zmpl dependency in Jetzig tomorrow when I'm not half-asleep. : )
